# Generated by Django 6.0.3 on 2026-05-02 17:36

import admin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudReport',
            fields=[
                ('id', models.CharField(db_column='report_id', max_length=36, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('evidence_urls', models.JSONField(db_column='evidence_urls', default=list)),
                ('visited_property', models.BooleanField(db_column='visited_property', default=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'fraud_reports',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LandlordProfile',
            fields=[
                ('id', models.CharField(db_column='landlord_id', max_length=36, primary_key=True, serialize=False)),
                ('trust_score', models.IntegerField(db_column='trust_score', default=0)),
                ('is_phone_verified', models.BooleanField(db_column='is_phone_verified', default=False)),
                ('is_id_verified', models.BooleanField(db_column='is_id_verified', default=False)),
                ('is_landlord_verified', models.BooleanField(db_column='is_landlord_verified', default=False)),
                ('verification_status', models.CharField(db_column='verification_status', default='pending', max_length=32)),
                ('organisation_name', models.CharField(blank=True, db_column='organisation_name', max_length=255, null=True)),
                ('is_organisation', models.BooleanField(db_column='is_organisation', default=False)),
            ],
            options={
                'db_table': 'landlord_profiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.CharField(db_column='listing_id', max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('address', models.CharField(max_length=255)),
                ('amenities', models.JSONField(default=list)),
                ('bedroom_type', models.CharField(blank=True, db_column='bedroom_type', max_length=64, null=True)),
                ('main_walking_minutes', models.IntegerField(blank=True, db_column='main_walking_min', null=True)),
                ('chiromo_walking_minutes', models.IntegerField(blank=True, db_column='chiromo_walking_min', null=True)),
                ('parklands_walking_minutes', models.IntegerField(blank=True, db_column='parklands_walking_min', null=True)),
                ('status', models.CharField(default='draft', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'listings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('photo_url', models.CharField(db_column='photo_url', max_length=500)),
                ('is_primary', models.BooleanField(db_column='is_primary', default=False)),
                ('display_order', models.IntegerField(db_column='display_order', default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'listing_photos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(db_column='user_id', max_length=36, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('role', models.CharField(default='student', max_length=32)),
                ('first_name', models.CharField(blank=True, db_column='first_name', max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, db_column='last_name', max_length=150, null=True)),
                ('profile_photo', models.CharField(blank=True, db_column='profile_photo', max_length=255, null=True)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.CharField(default=admin.models.generate_uuid_str, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(db_column='password_hash', max_length=255)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'admin_users',
            },
        ),
    ]
